apiVersion: "kafka.strimzi.io/v1beta2"
kind: "KafkaConnector"
metadata:
  name: my-connector
  labels:
    strimzi.io/cluster: my-connect-cluster-test
spec:
  class: io.debezium.connector.mysql.MySqlConnector
  tasksMax: 1
  config:
    tasks.max: 1
    database.hostname: mysql.mariadb.svc
    database.port: 3306
    database.user: mysqluser
    database.password: mysqlpw
    topic.prefix: mysql
    schema.history.internal.kafka.bootstrap.servers: my-cluster-kafka-bootstrap:9092
    schema.history.internal.kafka.topic: my-topic
